### PR TITLE
feat: use route.lazy

### LINKED ISSUE #48: Routes with dashes throw error
If you create a route with a dash in the name, and a handle, you get something like:

```
Uncaught SyntaxError: Unexpected token '-' (at __x00__virtual:routes:3:104)
```

The generated code looks like this:

```ts
import { handle as src_routes_some-thing_index_HANDLE } from '/src/routes/some-thing/index.tsx';
```

On a related note, have you considered using Route.lazy to load handles etc?

- https://reactrouter.com/en/main/route/lazy
- https://remix.run/blog/lazy-loading-routes

### PR DESCRIPTION
**Pull request by penx**
Closes #48 

React Router has a new feature called Route.lazy. If we use this instead of React.lazy, we don't need to load each handle, loader etc. in individually:

-  https://reactrouter.com/en/main/route/lazy
- https://remix.run/blog/lazy-loading-routes

### CODE REVIEW

**Comment by mammadataei** [comment]
@penx Thanks a lot for your contribution. I didn't know about the `lazy` property. It really simplified the code. 

The only problem is that I think it introduces a breaking change since the peer-dependency version needs a bump, and also doesn't support the `ErrorBoundary` export (a convention that I introduced on top of the remix convention because it made more sense to me).

Let's fix the tests and make sure everything works properly, then we can release a major version.

**Comment by penx** [comment]
@mammadataei are you still interested in adding this?

**Review by mammadataei — APPROVED** [review]

**Comment by mammadataei** [comment]
Oh, sorry. I was busy back then and then completely forgot about your PR. Merged. 
Thanks again for your contribution.

**Comment by mammadataei** [comment]
Released in [v2.0.0](https://github.com/mammadataei/vite-plugin-remix-router/releases/tag/v2.0.0).

**Pull request merged**
